FROM lscr.io/linuxserver/chromium:latest

# Patch /defaults/default.conf so init-nginx generates /etc/nginx/sites-available/default
# with the /cdp/ reverse proxy location block (mapping /cdp/ -> http://127.0.0.1:9222/)
RUN sed -i '/location SUBFOLDER {/i \  location /cdp/ {\n    proxy_pass http://127.0.0.1:9222/;\n    proxy_http_version 1.1;\n    proxy_set_header Upgrade $http_upgrade;\n    proxy_set_header Connection "upgrade";\n    proxy_set_header Host $host;\n    proxy_set_header X-Real-IP $remote_addr;\n    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n    proxy_read_timeout 3600s;\n    proxy_send_timeout 3600s;\n  }' /defaults/default.conf

# Patch /usr/bin/wrapped-chromium to exec chromium directly for clean signal handling
RUN sed -i 's|^\${BIN}|exec \${BIN}|' /usr/bin/wrapped-chromium

# Install s6-overlay v3 longrun service for Chromium autostart
COPY docker/s6-rc.d/svc-chromium /etc/s6-overlay/s6-rc.d/svc-chromium
RUN chmod 755 /etc/s6-overlay/s6-rc.d/svc-chromium/run \
    && touch /etc/s6-overlay/s6-rc.d/user/contents.d/svc-chromium
